name: my_env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - numpy=1.19.1 
  - pandas=0.25.3
  - h5py=2.10.0
  - tensorflow-gpu=1.14
  - pillow=8.0.1
  - pip=21.2.2
  - pip:
    - folium==0.14.0
    - Keras==2.2.4    
    - matplotlib==3.3.2
    - scipy==1.5.3
    - scikit-learn==0.23.2
    - feather-format==0.4.1
    - keras-vggface==0.6
    - opencv-contrib-python==4.4.0.44
    - beautifulsoup4==4.9.3
    - mtcnn==0.1.0
    - plotly==5.0.0
    - seaborn==0.11.0
